services:
  ubuntu:
    build: .
    container_name: linux-ubuntu
    hostname: ubuntu
    tty: true
    stdin_open: true
    deploy:
      resources:
        limits:
          # cpus: '0.5'
          memory: 512M
